[project]
name = "pylegv8"
version = "0.1.0"
description = "Python-based LEGv8 Assembly Simulator with GUI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PyQt6>=6.4.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0"
]
